title: Laura Yu Zheng
position: Ph.D. Student
affiliation: University of Maryland
affiliation_link: https://www.cs.umd.edu/
email: lyzheng (at) umd.edu
keywords: laura zheng, zheng laura, lyzheng, yu zheng, laurayuzheng
google_scholar: https://scholar.google.com/citations?user=kGUj-dIAAAAJ&hl=en
cv_link: ./assets/docs/laura_grad_cv.pdf
github_link: https://github.com/laurayuzheng/
linkedin: https://www.linkedin.com/in/laurayuzheng/
twitter: https://twitter.com/laurayuzheng/
avatar: ./assets/img/fall_headshot.png 
# google_analytics: UA-111540567-4
favicon: ./assets/img/car_icon.png
favicon_dark: ./assets/img/car_icon.png
description: Laura Zheng is a 3rd year CS PhD student at the University of Maryland. Her research lies in applications of computer vision, machine learning, and VR to autonomous driving and simulation.
# canonical: https://www.mpi-inf.mpg.de/~yaliu/
# imprint: https://imprint.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu
# data_protection: https://data-protection.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu?lang=en

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
